spring:
  application:
    name: pdf-worker

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/

server:
  port: 8082

#liumapp:
#  digitalsign:
#    service:
#      keystore:
#        keyStoreSavePath: /usr/local/tomcat/project/spring-cloud-digital-sign/

