spring:
  application:
    name: keystore-worker

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/

server:
  port: 8081

liumapp:
  digitalsign:
    service:
      keystore:
        keyStoreSavePath: /usr/local/tomcat/project/spring-cloud-digital-sign/