spring:
  application:
    name: tianwei-test
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: digital-sign-config-server
      profile: dev
      label: master
server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/