spring:
  application:
    name: @project.artifactId@

server:
  port: 2333

eureka:
  client:
    service-url:
      defaultZone: http://sign-eureka:1234/eureka/
zuul:
  routes:
    keystore-worker:
      serviceId: keystore-worker
      path: /**
    pdf-worker:
      serviceId: pdf-worker
      path: /**
    sign-demo:
      serviceId: sign-demo
      path: /**


