spring:
  application:
    name: digital-sign-gateway

server:
  port: 2333

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/
zuul:
  routes:
    keystore-worker:
      serviceId: keystore-worker
      path: /**
    pdf-worker:
      serviceId: pdf-worker
      path: /**

